### ISSUE TITLE
travis build failing in 0.6 and 0.8 due to ^ versions in transitive dependencies

### ISSUE THREAD

**Issue by michaelficarra** [estools/esquery#43]
```
npm ERR! Error: No compatible version found: bn.js@'^0.15.0'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5","0.1.6","0.1.7","0.2.0","0.2.1","0.2.2","0.3.0","0.3.1","0.4.0","0.4.1","0.4.2","0.4.3","0.4.4","0.5.0","0.5.1","0.5.2","0.5.3","0.5.4","0.6.0","0.7.0","0.7.1","0.8.0","0.8.1","0.9.0","0.10.0","0.10.1","0.11.0","0.11.1","0.11.2","0.11.3","0.11.4","0.11.5","0.11.6","0.11.7","0.12.0","0.13.0","0.13.1","0.13.2","0.13.3","0.14.0","0.14.1","0.14.2","0.15.0","0.15.1","0.15.2","0.16.0"]
npm ERR!     at installTargetsError (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /home/travis/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:641:10
```

I say we drop them from the CI process. Nobody is seriously using them anyway (or at least shouldn't be due to security concerns).

**Comment by michaelficarra** [comment]
Fixed by https://github.com/estools/esquery/commit/d1bafbf7db73f37bf2d2e7c3fbcf3747f58ba6a1.
